config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'card_templates#index'

  get '/admin', to: 'admin#index'

  get '/admin/signout', to: 'sessions#destroy'

  get '/support', to: 'cards#support'

  resources :card_templates, only: [:index] do
    resources :cards, except: [:index, :destroy]
  end

  resources :charges, only: [:create]

  resources :sessions, only: [:create, :destroy]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :recipient_name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  belongs_to :card_template
end

app/models/card_template.rb
class CardTemplate < ApplicationRecord
  validates :greeting, presence: true
  validates :image_file, presence: true

  has_many :cards
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize

  def index
    @cards = Card.all
  end

  private

  def current_user
    if session[:user_id]
      @current_user ||= AdminUser.find(session[:user_id])
    end
  end

  def authorize
    render 'login' unless current_user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/card_templates_controller.rb
class CardTemplatesController < ApplicationController

  def index
    @templates = CardTemplate.all
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
    @template = CardTemplate.find(params[:card_template_id])
  end

  def create
    new_card = Card.new(card_params)

    if new_card.save
      new_card.update(session_id: session.id)
      redirect_to card_template_card_url(id: new_card.id)
    else
      flash[:error] = "Unable to create this card for some reason."
      redirect_to new_card_template_card_url
    end
  end

  def show
    @template = CardTemplate.find(params[:card_template_id])
    @card = Card.find(params[:id])
    check_session
  end

  def edit
    @template = CardTemplate.find(params[:card_template_id])
    @card = Card.find(params[:id])
    check_session
  end

  def update
    @template = CardTemplate.find(params[:card_template_id])
    @card = Card.find(params[:id])
    check_session

    @card.update(card_params)
  end

  def support
    @context = 'Contact Support'
    @template = CardTemplate.find_by(greeting: "Sorry you feel that way")
    @prefill = {
      recipient_name: 'SorryYouFeelThatWay Support Team',
      street_address: '1777 9th St',
      city: 'Oakland',
      state: 'CA',
      zip_code: '94607'
    }
    render 'new'
  end

  private

  def check_session
    unless @card.session_id == session.id
      redirect_to new_card_template_card_url(card_template_id: @template.id)
    end
  end

  def card_params
    params.require(:card).permit(:custom_message, :signature, :recipient_name,
                  :street_address, :city, :state, :zip_code, :card_template_id)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    Stripe.api_key = Rails.configuration.stripe[:secret_key]
    @amount = 499
    unless Card.exists?(params[:card_id])
      redirect_to '/'
    else
      @card = Card.find(params[:card_id])

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      @charge = Stripe::Charge.create(
        :customer         => customer.id,
        :amount           => @amount,
        :description      => 'Handwritten greeting card',
        :currency         => 'usd',
        :receipt_email    => params[:stripeEmail],
        :shipping         => {
          :name           => @card.recipient_name,
          :address        => {
            :line1        => @card.street_address,
            :city         => @card.city,
            :state        => @card.state,
            :postal_code  => @card.zip_code
          }
        },
        :metadata         => {
          :card_id        => @card.id,
          :greeting       => @card.card_template.greeting,
          :custom_message => @card.custom_message,
          :signature      => @card.signature
        }
      )
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    if Card.exists?(params[:card_id])
      card = Card.find(params[:card_id])
      redirect_to card_template_card_path(
        id: card.id,
        card_template_id: card.card_template_id
      )
    else
      redirect_to '/'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = AdminUser.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
    end
    redirect_back(fallback_location: '/')
  end

  def destroy
    session[:user_id] = nil
    redirect_back(fallback_location: '/')
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_templates_helper.rb
module CardTemplatesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/index.html.erb
<h1> Admin </h1>

  <h2> Ordered Cards </h2>

    <ul class="ordered_cards">
      <% @cards.each do |card| %>
        <li>
          <%= "#{card.id} - #{card.card_template.greeting} - #{card.custom_message}" %>
        </li>
      <% end %>
    </ul>

app/views/admin/login.html.erb
<h1> Admin Login </h1>

<%= form_tag("/sessions", method: "post") do %>
  <label for="username">username</label>
  <input required="required" type="text" name="username" id="username" />
  <br>
  <label for="password">password</label>
  <input required="required" type="password" name="password" id="password" />
  <br>
  <button type="submit" class="btn btn-default">Submit</button>
<% end %>

app/views/card_templates/index.html.erb
<div class="container-fluid">

  <div class="header">
    <div class="row">
      <div class="col">
        <h1> Let them know what you really think </h1>
      </div>
      <div class="col">
        <a
          role="button"
          class="support btn btn-outline-secondary float-right"
          href="/support"
        >
          Support
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p>Custom handwritten notes delivered by post: $4.99</p>
      </div>
    </div>
  </div>

  <div class="row">
    <% @templates.each do |template| %>
      <div class="col-xs-10 col-md-6">
        <a
          href="/card_templates/<%= template.id %>/cards/new"
          id="template-<%= template.id %>-create"
        >
          <img
            id="template-<%= template.id %>-image"
            src="/assets/<%= template.image_file %>"
            class="img-fluid img-thumbnail"
            alt="<%= template.greeting %> template"
          >
        </a>
      </div>
    <% end %>
  </div>

</div>

app/views/cards/_form.html.erb
<% @card ||= Card.new(@prefill) %>

<%= form_tag card_template_cards_path(@template.id), {class: "order-form"} do %>

  <input type="hidden" name="card[card_template_id]" value="<%= @template.id %>">

  <div class="row">
    <div class="col-xs-10 col-md-6">
      <div class="field row">
        <div class="col-4 form-field-label">
          <label for="card_recipient_name">Recipient Name
          </label>
        </div>
        <div class="col-8">
          <input required="required" class="form-control" type="text"
            name="card[recipient_name]" id="card_recipient_name"
            value="<%= @card.recipient_name %>"/>
        </div>
      </div>
      <div class="field row">
        <div class="col-4 form-field-label">
          <label for="card_street_address">Address
          </label>
        </div>
        <div class="col-8">
          <input required="required" class="form-control" type="text"
            name="card[street_address]" id="card_street_address"
            value="<%= @card.street_address %>" />
        </div>
      </div>
      <div class="field row">
        <div class="col-4 form-field-label">
          <label for="card_city">City</label>
        </div>
        <div class="col-8">
          <input required="required" class="form-control" type="text"
            name="card[city]" id="card_city"
            value="<%= @card.city %>" />
        </div>
      </div>
      <div class="field row">
        <div class="col-4 form-field-label">
          <label for="card_state">State</label>
        </div>
        <div class="col-8">
          <input required="required" class="form-control" type="text"
            name="card[state]" id="card_state"
            value="<%= @card.state %>" />
        </div>
      </div>
      <div class="field row form-group">
        <div class="col-4 form-field-label">
          <label for="card_zip_code">Zip Code</label>
        </div>
        <div class="col-8">
          <input required="required" class="form-control" type="text"
            name="card[zip_code]" id="card_zip_code"
            value="<%= @card.zip_code %>" />
        </div>
      </div>
      <div class="field row form-group">
        <div class="col-4 form-field-label">
          <label for="card_custom_message">Custom Message</label>
        </div>
        <div class="col-8">
          <textarea class="form-control" rows="3" name="card[custom_message]"
            id="card_custom_message"><%= @card.custom_message %></textarea>
        </div>
      </div>
      <div class="field row form-group">
        <div class="col-4 form-field-label">
          <label for="card_signature">Signature</label>
        </div>
        <div class="col-8">
          <input class="form-control" type="text" name="card[signature]"
            id="card_signature" value="<%= @card.signature %>" />
        </div>
      </div>
      <div class="row form-group">
        <div class="col-4"></div>
        <div class="col-8">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </div>
    </div>
    <div class="col-xs-10 col-md-6">
      <img id="template-<%= @template.id %>-image"
           src="/assets/<%= @template.image_file %>"
           class="img-fluid img-thumbnail"
           alt="<%= @template.greeting %>">
    </div>
  </div>

<% end %>

app/views/cards/edit.html.erb
<div class="container-fluid">

  <div class="header">
    <div class="row">
      <div class="col">
        <h1> Edit Your Message </h1>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p>  </p>
      </div>
    </div>
  </div>

  <%= render 'form' %>

</div>

app/views/cards/new.html.erb
<% @context ||= 'Customize Your Message' %>

<div class="container-fluid">

  <div class="header">
    <div class="row">
      <div class="col">
        <h1><%= @context %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p>  </p>
      </div>
    </div>
  </div>

  <%= render 'form' %>

</div>

app/views/cards/show.html.erb
<div class="container-fluid">

  <div class="header">
    <div class="row">
      <div class="col">
        <h1> Review Order </h1>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p> Total: $4.99 </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-md-6">
      <div class="row">
        <div class="col-4 form-field-label">
          Recipient
        </div>
        <div class="col-8">
          <div id="recipient-details">
            <ul>
              <li><%= @card.recipient_name %></li>
              <li><%= @card.street_address %></li>
              <li><%= @card.city %></li>
              <li><%= @card.state %></li>
              <li><%= @card.zip_code %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-4 form-field-label">
          Message
        </div>
        <div class="col-8">
          <div id="custom-card-details">
            <p class="message"><%= @card.custom_message %></p>
            <p class="signature"><%= @card.signature %></p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-4"> </div>
        <div class="col-8">
          <div id="payment-buttons">

            <%= form_tag charges_path do %>
              <article class="payment-area">
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
              </article>

              <input type="hidden" name="card_id" value="<%= @card.id %>">

              <a href="<%= edit_card_template_card_path %>">
                <button role="button" class="btn btn-default">Edit</button>
              </a>

              <script src="https://checkout.stripe.com/checkout.js"
                class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Handwritten card delivered by post"
                data-amount="499"
                data-locale="auto">
              </script>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-10 col-md-6">
      <img id="template-<%= @template.id %>-image"
           src="/assets/<%= @template.image_file %>"
           class="img-fluid img-thumbnail"
           alt="<%= @template.greeting %>"
      >
    </div>
  </div>
</div>

app/views/charges/create.html.erb
<div>It is done.</div>

<div>There is no turning back now.</div>

<div>I wonder what will they say?</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SorryYouFeelThatWay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Goudy+Bookletter+1911" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-108449743-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-108449743-1');
    </script>


  </head>

  <body>
    <%= yield %>
  </body>
</html>